//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzDoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;css/bootstrap.min.css&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;css/treejs.min.css&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://use.fontawesome.com/releases/v5.0.13/css/all.css&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;js/trumbowyg/ui/trumbowyg.min.css&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;css/style.css&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;css/navtree.css&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  {{navbar}}
        ///
        ///  &lt;main role=&quot;main&quot; class=&quot;row&quot; style=&quot;margin-top: 60px;&quot; class=&quot;fixed-t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_template {
            get {
                return ResourceManager.GetString("base_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Property Tables*/
        ///
        ///table {
        ///  border-collapse: collapse;
        ///  border: 2px solid rgb(200, 200, 200);
        ///  letter-spacing: 1px;
        ///  font-size: 0.8rem;
        ///}
        ///
        ///td, th {
        ///  border: 1px solid rgb(190, 190, 190);
        ///  padding: 10px 20px;
        ///}
        ///
        ///th {
        ///  background-color: rgb(235, 235, 235);
        ///}
        ///
        ///td {
        ///  text-align: center;
        ///}
        ///
        ///tr:nth-child(even) td {
        ///  background-color: rgb(250, 250, 250);
        ///}
        ///
        ///tr:nth-child(odd) td {
        ///  background-color: rgb(245, 245, 245);
        ///}
        ///
        ///caption {
        ///  padding: 10px;
        ///}
        ///.
        /// </summary>
        internal static string content_css {
            get {
                return ResourceManager.GetString("content_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;{{name}}&quot; class=&quot;content&quot;&gt;
        ///  {{content}}
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string content_entry_template {
            get {
                return ResourceManager.GetString("content_entry_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;content-link-inline&quot; id=&quot;{{link}}-link-inline&quot;&gt;{{name}}&lt;/p&gt;.
        /// </summary>
        internal static string content_link_inline_template {
            get {
                return ResourceManager.GetString("content_link_inline_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a class=&quot;dropdown-item&quot; href=&quot;{{link}}&quot;&gt;{{text}}&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string navbar_dropdownitem_entry_template {
            get {
                return ResourceManager.GetString("navbar_dropdownitem_entry_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;nav-item dropdown&quot;&gt;
        ///  &lt;a class=&quot;nav-link dropdown-toggle&quot; href=&quot;#&quot; id=&quot;navbarDropdown&quot; role=&quot;button&quot; data-bs-toggle=&quot;dropdown&quot;
        ///     aria-expanded=&quot;false&quot;&gt;
        ///    {{text}}
        ///  &lt;/a&gt;
        ///  &lt;ul class=&quot;dropdown-menu&quot; aria-labelledby=&quot;navbarDropdown&quot;&gt;
        ///    {{entries}}   
        ///    &lt;li&gt;
        ///      &lt;hr class=&quot;dropdown-divider&quot;&gt;
        ///    &lt;/li&gt;
        ///    &lt;li&gt;&lt;a class=&quot;dropdown-item&quot; href=&quot;#&quot;&gt;Something else here&lt;/a&gt;&lt;/li&gt;
        ///  &lt;/ul&gt;
        ///&lt;/li&gt;.
        /// </summary>
        internal static string navbar_dropdownitem_template {
            get {
                return ResourceManager.GetString("navbar_dropdownitem_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;nav-item&quot;&gt;
        ///  &lt;a class=&quot;nav-link active&quot; aria-current=&quot;page&quot; href=&quot;{{link}}&quot;&gt;{{text}}&lt;/a&gt;
        ///&lt;/li&gt;.
        /// </summary>
        internal static string navbar_item_template {
            get {
                return ResourceManager.GetString("navbar_item_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- &lt;nav class=&quot;navbar navbar-expand-lg navbar-light bg-light&quot;&gt; --&gt;
        ///&lt;nav class=&quot;navbar navbar-expand-lg navbar-dark bg-dark&quot;&gt;
        ///
        ///  &lt;div class=&quot;container-fluid&quot;&gt;
        ///    &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;Zusagenframework&lt;/a&gt;
        ///    &lt;button class=&quot;navbar-toggler&quot; type=&quot;button&quot; data-bs-toggle=&quot;collapse&quot; data-bs-target=&quot;#navbarSupportedContent&quot;
        ///      aria-controls=&quot;navbarSupportedContent&quot; aria-expanded=&quot;false&quot; aria-label=&quot;Toggle navigation&quot;&gt;
        ///      &lt;span class=&quot;navbar-toggler-icon&quot;&gt;&lt;/span&gt;
        ///    &lt;/button&gt;
        ///    &lt;div [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string navbar_template {
            get {
                return ResourceManager.GetString("navbar_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li id=&quot;{{name}}-link&quot; class=&quot;content-link&quot;&gt;{{name}}&lt;/li&gt;.
        /// </summary>
        internal static string navtree_contentLink_template {
            get {
                return ResourceManager.GetString("navtree_contentLink_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Remove default bullets */
        ///
        ////* Navigation Tree */
        ////* ----------------------------------------------------------------------------------------------- */
        ///
        ///.treeview {
        ///  width: 20%;
        ///  height: 1000px;
        ///  float: left;
        ///  margin: 20px;
        ///  margin-right: 20px;
        ///  overflow-y: scroll;
        ///}
        ///
        ///ul, #navTree {
        ///  list-style-type: none;
        ///  padding-inline-start: 20px;
        ///}
        ///
        ////* Remove margins and padding from the parent ul */
        ///
        ///#navTree {
        ///  margin: 0;
        ///  padding: 0;
        ///}
        ///
        ////* Style the caret */
        ///
        ///.caret {
        ///  curso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string navtree_css {
            get {
                return ResourceManager.GetString("navtree_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var toggler = document.getElementsByClassName(&quot;caret&quot;);
        ///var contentLinks = document.getElementsByClassName(&quot;content-link&quot;);
        ///var contentLinksInline = document.getElementsByClassName(&quot;content-link-inline&quot;);
        ///var filterBox = document.getElementById(&quot;filter-box&quot;);
        ///var currentActiveContentId = &quot;&quot;
        ///var currentActiveLinkId = &quot;&quot;
        ///var i;
        ///
        ///window.onhashchange = function () {
        ///  console.log(&quot;On Window Change&quot;, location.hash);
        ///  onContentLinkClicked(location.hash.replace(&quot;#&quot;, &quot;&quot;));
        ///}
        ///
        ///window.onload = function  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string navtree_js {
            get {
                return ResourceManager.GetString("navtree_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{parentVariable}}.addChild({{childVariable}});.
        /// </summary>
        internal static string navtree_js_child_template {
            get {
                return ResourceManager.GetString("navtree_js_child_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var {{nodeName}} = new TreeNode(&quot;{{nodeName}}&quot;);
        ///{{nodeName}}.on(&apos;select&apos;, function (e, node) {
        ///    onNodeClick({{nodeName}})
        ///});
        ///
        ///.
        /// </summary>
        internal static string navtree_js_item_template {
            get {
                return ResourceManager.GetString("navtree_js_item_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var root = new TreeNode(&quot;Zusagenframework&quot;);
        ///{{items}}
        ///treeView = new TreeView(root, &quot;#container&quot;);
        ///setupTree();.
        /// </summary>
        internal static string navtree_js_template {
            get {
                return ResourceManager.GetString("navtree_js_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;mainhead&quot;&gt;{{title}}&lt;/p&gt;
        ///&lt;form class=&quot;d-flex&quot;&gt;
        ///  &lt;input id=&quot;filter-box&quot; class=&quot;form-control me-2&quot; type=&quot;search&quot; placeholder=&quot;Filter&quot; aria-label=&quot;Search&quot;&gt;
        ///&lt;/form&gt;
        ///&lt;hr&gt;
        ///&lt;div id=&quot;container&quot;&gt;&lt;/div&gt;.
        /// </summary>
        internal static string navtree_template {
            get {
                return ResourceManager.GetString("navtree_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;
        ///  &lt;span class=&quot;caret&quot;&gt;{{name}}&lt;/span&gt;
        ///  &lt;ul class=&quot;nested&quot;&gt;
        ///    {{children}}
        ///  &lt;/ul&gt;
        ///&lt;/li&gt;.
        /// </summary>
        internal static string navtree_toggler_template {
            get {
                return ResourceManager.GetString("navtree_toggler_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;{{name}}&lt;/h2&gt;
        ///&lt;p&gt;{{content}}&lt;/p&gt;.
        /// </summary>
        internal static string summary_template {
            get {
                return ResourceManager.GetString("summary_template", resourceCulture);
            }
        }
    }
}
